### ISSUE TITLE
This seems to be missing some files

### ISSUE THREAD

**Issue by ChaselLau666** [JINXER000/multiple-task-temporal-logic-planning#1]
Thanks for the great work I ran into some problems when trying to run it. It seemed like some key files were missing. For example
![image](https://github.com/JINXER000/multiple-task-temporal-logic-planning/assets/139679124/6acf26e3-5e03-4f32-ac51-5bcc523b0c38)
![image](https://github.com/JINXER000/multiple-task-temporal-logic-planning/assets/139679124/4a82cd27-1aee-40e3-9f21-81da15656bb7)
![image](https://github.com/JINXER000/multiple-task-temporal-logic-planning/assets/139679124/3913537b-5a34-438d-bfe4-c6f849a3c32d)

**Comment by JINXER000** [comment]
Sorry for the confusion. The file you mention is a DFA in Graphviz format. You can generate the DFA from [this file](https://github.com/JINXER000/multiple-task-temporal-logic-planning/blob/master/LTLMP/src/formula_parser/ltlf2dfa.py). Before executing this file, you should follow the instructions in the readme to install LTLf2DFA. Additionally, replace all the directories (which are from my own laptop) with yours.
Note that the code is still dirty right now and I am putting in continual effort to improve it.
